services: 
  db:
    image: postgres:alpine
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=dockeruser
    - POSTGRES_PASSWORD=$PG_PASSWORD
    - POSTGRES_DB=leaderboard
    volumes:
    - pg-data:/var/lib/postgresql/data
    - ./db:/docker-entrypoint-initdb.d
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@acme.com
      PGADMIN_DEFAULT_PASSWORD: $DB_PASSWORD
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  web1:
    build: web
    expose:
      - "3000"
      #ports:
      #- 3000:3000
      #- 3000-3003:3000 this gave me a too long to respond error on the site 
    environment:
    - DB_HOST=db
    - POSTGRES_USER=dockeruser
    - POSTGRES_PASSWORD=$PG_PASSWORD
    depends_on:
    - db

  web2:
    build: web
    expose:
      - "3000"
    environment:
    - DB_HOST=db
    - POSTGRES_USER=dockeruser
    - POSTGRES_PASSWORD=$PG_PASSWORD
    depends_on:
    - db

  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes: 
      -  ./nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - web1
      - web2 

volumes: 
  pg-data:
  pgadmin-data:
