services: 
  db:
    image: postgres:alpine
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=dockeruser
    - POSTGRES_PASSWORD=$PG_PASSWORD
    - POSTGRES_DB=leaderboard
    volumes:
    - pg-data:/var/lib/postgresql/data
    - ./db:/docker-entrypoint-initdb.d
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@acme.com
      PGADMIN_DEFAULT_PASSWORD: $DB_PASSWORD
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes: 
  pg-data:
  pgadmin-data:
