version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dockeruser
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=leaderboard
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@acme.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
  
  web:
    image: myapp_web:latest
    build: web
    ports:
      - 3000-3003:3000
    environment:
      - DB_HOST=db
      - POSTGRES_USER=dockeruser
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    depends_on:
      - db
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

volumes: 
  pg-data:
    driver: local
  pgadmin-data:
    driver: local
